import type { Metadata, Viewport } from "next";
import { Google_Sans } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { QueryProvider } from "@/contexts/query-provider";

const googleSans = Google_Sans({
	variable: "--font-sans",
	subsets: ["latin"],
	adjustFontFallback: false,
	fallback: ["system-ui", "sans-serif"],
});

export const metadata: Metadata = {
	title: "Mult Agent",
	description: "Generated by create next app",
};

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body
				className={`${googleSans.variable} font-sans antialiased min-h-screen`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem={false}
					disableTransitionOnChange
				>
					<QueryProvider>{children}</QueryProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
