using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Client.Migrations
{
    /// <inheritdoc />
    public partial class a : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_OrderProducts_Orders_OrderId",
                table: "OrderProducts",
                schema: "client");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Orders",
                table: "Orders",
                schema: "client");

            migrationBuilder.AddColumn<int>(
                name: "Id_temp",
                schema: "client",
                table: "Orders",
                type: "integer");

            migrationBuilder.Sql(@"
                WITH numbered_rows AS (
                    SELECT ""Id"", ROW_NUMBER() OVER (ORDER BY ""Id"") as new_id
                    FROM client.""Orders""
                )
                UPDATE client.""Orders"" o
                SET ""Id_temp"" = nr.new_id
                FROM numbered_rows nr
                WHERE o.""Id"" = nr.""Id""
            ");

            migrationBuilder.DropColumn(
                name: "Id",
                schema: "client",
                table: "Orders");

            migrationBuilder.RenameColumn(
                name: "Id_temp",
                schema: "client",
                table: "Orders",
                newName: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Orders",
                schema: "client",
                table: "Orders",
                column: "Id");

            migrationBuilder.Sql(@"
                ALTER TABLE client.""Orders"" 
                ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE client.""OrderProducts"" 
                ALTER COLUMN ""OrderId"" DROP NOT NULL
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE client.""OrderProducts"" 
                ALTER COLUMN ""OrderId"" TYPE integer USING NULL
            ");

            migrationBuilder.Sql(@"
                WITH uuid_to_int AS (
                    SELECT ""Id"", ROW_NUMBER() OVER (ORDER BY ""Id"") as new_id
                    FROM client.""Orders""
                )
                UPDATE client.""OrderProducts"" op
                SET ""OrderId"" = ui.new_id
                FROM uuid_to_int ui
                WHERE op.""OrderId""::text = ui.""Id""::text
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE client.""OrderProducts"" 
                ALTER COLUMN ""OrderId"" SET NOT NULL
            ");

            migrationBuilder.AddForeignKey(
                name: "FK_OrderProducts_Orders_OrderId",
                schema: "client",
                table: "OrderProducts",
                column: "OrderId",
                principalSchema: "client",
                principalTable: "Orders",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_OrderProducts_Orders_OrderId",
                table: "OrderProducts",
                schema: "client");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Orders",
                table: "Orders",
                schema: "client");

            migrationBuilder.Sql(@"
                ALTER TABLE client.""Orders"" 
                ALTER COLUMN ""Id"" DROP IDENTITY
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE client.""Orders"" 
                ALTER COLUMN ""Id"" TYPE uuid USING gen_random_uuid()
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE client.""OrderProducts"" 
                ALTER COLUMN ""OrderId"" DROP NOT NULL
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE client.""OrderProducts"" 
                ALTER COLUMN ""OrderId"" TYPE uuid USING gen_random_uuid()
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE client.""OrderProducts"" 
                ALTER COLUMN ""OrderId"" SET NOT NULL
            ");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Orders",
                schema: "client",
                table: "Orders",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_OrderProducts_Orders_OrderId",
                schema: "client",
                table: "OrderProducts",
                column: "OrderId",
                principalSchema: "client",
                principalTable: "Orders",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}